[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#01051c"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#2C3333"

# Color used for almost all text.
textColor = "#fff"